//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientProtocol
    {
        public int Id { get; set; }
        public int PatientID { get; set; }
        public int ProtocolID { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public System.DateTime Last_Update { get; set; }
        public int Last_Updated_Interval { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Protocol Protocol { get; set; }
    }
}
