//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PatientDatabaseEntities : DbContext
    {
        public PatientDatabaseEntities()
            : base("name=PatientDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Pathology> Pathologies { get; set; }
        public virtual DbSet<PatientPathology> PatientPathologies { get; set; }
        public virtual DbSet<Medication> Medications { get; set; }
        public virtual DbSet<PatientMedication> PatientMedications { get; set; }
        public virtual DbSet<Past_Medical_History> Past_Medical_History { get; set; }
        public virtual DbSet<PatientPast_Medical_History> PatientPast_Medical_History { get; set; }
        public virtual DbSet<PatientProblem> PatientProblems { get; set; }
        public virtual DbSet<PatientSurgery> PatientSurgeries { get; set; }
        public virtual DbSet<PatientTrauma> PatientTraumas { get; set; }
        public virtual DbSet<PatientTreatment> PatientTreatments { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<Surgery> Surgeries { get; set; }
        public virtual DbSet<Trauma> Traumata { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
        public virtual DbSet<Outcome> Outcomes { get; set; }
        public virtual DbSet<PatientOutcome> PatientOutcomes { get; set; }
        public virtual DbSet<PatientProtocol> PatientProtocols { get; set; }
        public virtual DbSet<Protocol> Protocols { get; set; }
        public virtual DbSet<ProtocolOutcome> ProtocolOutcomes { get; set; }
    }
}
