//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPast_Medical_History
    {
        public int Id { get; set; }
        public int PatientID { get; set; }
        public int Past_Medical_HistoryID { get; set; }
    
        public virtual Past_Medical_History Past_Medical_History { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
